### ISSUE TITLE
update documentation for categories replacing oe_ids with taxonomy_ids

### ISSUE THREAD

**Issue by ddbaron** [codeforamerica/ohana-api-docs#2]
The doc here: http://codeforamerica.github.io/ohana-api-docs/#update-a-service39s-categories
specifies the use of `oe_ids` to update the categories for a service. The correct parameter name is `taxonomy_ids`

This is confusing because the use of any parameter (e.g. `foobar`) returns a success response with the json object, but the categories are not filled in.

This works:
`curl -X PUT "http://localhost:8080/api/services/30/categories" -d '{"taxonomy_ids": ["101", "102"]}' -H "X-Api-Token: <<fill in>>" -H "Content-Type: application/json" `

**Comment by monfresh** [comment]
Thanks for the report. I just fixed this. The [API endpoint that updates a service's categories](https://github.com/codeforamerica/ohana-api/blob/master/app/controllers/api/v1/services_controller.rb#L36-L42) is pretty basic. It doesn't do any error checking for the parameters. We haven't spent much time on the write portion of the API because it comes with a built-in web-based admin interface.

What is your use case for wanting to write to the database via an API call?
